Repository android-team-02/developer-study-platform, pull requests merged in 2024-01, with the labels that each got.

#17 소셜 로그인 화면 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sesac/developer_study_platform/Extensions.kt
  app/src/main/java/com/sesac/developer_study_platform/GithubService.kt
  app/src/main/java/com/sesac/developer_study_platform/LoginFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/MainActivity.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyApplication.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/User.kt
  app/src/main/res/drawable/bg_btn_login.xml
  app/src/main/res/drawable/ic_github_mark.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: feat, design

#15 앱 아이콘 변경 및 스플래시 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/sesac/developer_study_platform/Extensions.kt
  app/src/main/java/com/sesac/developer_study_platform/GithubService.kt
  app/src/main/java/com/sesac/developer_study_platform/LoginFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/MainActivity.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyApplication.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/User.kt
  app/src/main/res/drawable/bg_btn_login.xml
  app/src/main/res/drawable/ic_github_mark.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feat, design

#21 분야별 스터디 목록 화면 구현
  app/build.gradle.kts
  app/src/main/java/com/sesac/developer_study_platform/Category.kt
  app/src/main/java/com/sesac/developer_study_platform/CategoryAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/CategoryFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/GridSpaceItemDecoration.kt
  app/src/main/java/com/sesac/developer_study_platform/HomeFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/SearchCategoryFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/ViewPagerAdapter.kt
  app/src/main/res/drawable/line_tab.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search_category.xml
  app/src/main/res/layout/item_study_category.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/styles.xml
  build.gradle.kts
Labels: feat, design

#20 홈화면 나의 스터디 구현
  app/build.gradle.kts
  app/src/main/java/com/sesac/developer_study_platform/Category.kt
  app/src/main/java/com/sesac/developer_study_platform/CategoryAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/CategoryFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/GridSpaceItemDecoration.kt
  app/src/main/java/com/sesac/developer_study_platform/HomeFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/SearchCategoryFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/SpaceItemDecoration.kt
  app/src/main/java/com/sesac/developer_study_platform/Study.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/ViewPagerAdapter.kt
  app/src/main/res/drawable/ic_plus_home.xml
  app/src/main/res/drawable/line_tab.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search_category.xml
  app/src/main/res/layout/item_study_category.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle.kts
Labels: feat, design

#19 바텀내비게이션 구현
  app/build.gradle.kts
  app/src/main/java/com/sesac/developer_study_platform/Category.kt
  app/src/main/java/com/sesac/developer_study_platform/CategoryAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/CategoryFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/GridSpaceItemDecoration.kt
  app/src/main/java/com/sesac/developer_study_platform/HomeFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/MainActivity.kt
  app/src/main/java/com/sesac/developer_study_platform/SearchCategoryFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/SpaceItemDecoration.kt
  app/src/main/java/com/sesac/developer_study_platform/Study.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/ViewPagerAdapter.kt
  app/src/main/res/drawable/ic_account.xml
  app/src/main/res/drawable/ic_account_fill.xml
  app/src/main/res/drawable/ic_chat.xml
  app/src/main/res/drawable/ic_chat_fill.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_home_fill.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_plus_fill.xml
  app/src/main/res/drawable/ic_plus_home.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_fill.xml
  app/src/main/res/drawable/line_tab.xml
  app/src/main/res/drawable/selector_account.xml
  app/src/main/res/drawable/selector_chat.xml
  app/src/main/res/drawable/selector_home.xml
  app/src/main/res/drawable/selector_plus.xml
  app/src/main/res/drawable/selector_search.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search_category.xml
  app/src/main/res/layout/item_study_category.xml
  app/src/main/res/menu/menu_bnv.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle.kts
Labels: feat, design

#18 홈화면 레이아웃 구현
  app/build.gradle.kts
  app/src/main/java/com/sesac/developer_study_platform/Category.kt
  app/src/main/java/com/sesac/developer_study_platform/CategoryAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/CategoryFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/GridSpaceItemDecoration.kt
  app/src/main/java/com/sesac/developer_study_platform/HomeFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/MainActivity.kt
  app/src/main/java/com/sesac/developer_study_platform/SearchCategoryFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/SpaceItemDecoration.kt
  app/src/main/java/com/sesac/developer_study_platform/Study.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/ViewPagerAdapter.kt
  app/src/main/res/drawable/bg_ai.xml
  app/src/main/res/drawable/bg_android.xml
  app/src/main/res/drawable/bg_back_end.xml
  app/src/main/res/drawable/bg_etc.xml
  app/src/main/res/drawable/bg_front_end.xml
  app/src/main/res/drawable/bg_ios.xml
  app/src/main/res/drawable/ic_account.xml
  app/src/main/res/drawable/ic_account_fill.xml
  app/src/main/res/drawable/ic_arrow_forward.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_chat.xml
  app/src/main/res/drawable/ic_chat_fill.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_home_fill.xml
  app/src/main/res/drawable/ic_person.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_plus_fill.xml
  app/src/main/res/drawable/ic_plus_home.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_search_fill.xml
  app/src/main/res/drawable/line_tab.xml
  app/src/main/res/drawable/selector_account.xml
  app/src/main/res/drawable/selector_chat.xml
  app/src/main/res/drawable/selector_home.xml
  app/src/main/res/drawable/selector_plus.xml
  app/src/main/res/drawable/selector_search.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search_category.xml
  app/src/main/res/layout/item_study.xml
  app/src/main/res/layout/item_study_category.xml
  app/src/main/res/menu/menu_bnv.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle.kts
Labels: design

#35 홈화면, 분야별 스터디 목록 화면 데이터베이스 수정된 구조 적용
  app/src/main/java/com/sesac/developer_study_platform/data/Study.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/GridSpaceItemDecoration.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/UserStudyClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/category/CategoryAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/category/CategoryFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/StudyAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_study.xml
Labels: refactor

#16 [ 스터기 만들기 화면 ] 제한사항 처리, 이미지 권한 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sesac/developer_study_platform/DayTimeAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/Extensions.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyFormFragment.kt
  app/src/main/res/drawable/bg_study_input.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/layout/fragment_study_form.xml
  app/src/main/res/layout/item_day_time.xml
  app/src/main/res/layout/item_dropdown.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feat, design

#14 [ 스터디 만들기 화면 ] 스터디 기간, 요일, 시간 선택 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sesac/developer_study_platform/DayTime.kt
  app/src/main/java/com/sesac/developer_study_platform/DayTimeAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/DayTimeClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/Extensions.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyFormFragment.kt
  app/src/main/res/drawable/bg_study_input.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/layout/fragment_study_form.xml
  app/src/main/res/layout/item_day_time.xml
  app/src/main/res/layout/item_dropdown.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feat, design

#13 [ 스터디 만들기 화면 ] 대표 언어선택, 총 인원수 선택 드롭다운 메뉴 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sesac/developer_study_platform/DayTime.kt
  app/src/main/java/com/sesac/developer_study_platform/DayTimeAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/DayTimeClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/Extensions.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyFormFragment.kt
  app/src/main/res/drawable/bg_study_input.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/layout/fragment_study_form.xml
  app/src/main/res/layout/item_day_time.xml
  app/src/main/res/layout/item_dropdown.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feat, design

#12 [ 스터디 만들기 화면 ] 갤러리 이미지 추가, 카테고리, 스터디명, 스터디 내용 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sesac/developer_study_platform/data/DayTime.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/DayTimeClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/main/MainActivity.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/studyform/DayTimeAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/studyform/StudyFormFragment.kt
  app/src/main/res/color/selector_study_category.xml
  app/src/main/res/drawable/bg_study_input.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/selector_study_category_bg.xml
  app/src/main/res/layout/fragment_study_form.xml
  app/src/main/res/layout/item_day_time.xml
  app/src/main/res/layout/item_dropdown.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feat, design

#23 스터디 상세 화면 구현
  app/src/main/java/com/sesac/developer_study_platform/DetailFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/JoinStudyAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/JoinStudyListFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/MainActivity.kt
  app/src/main/java/com/sesac/developer_study_platform/Study.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/UserStudyRoom.kt
  app/src/main/java/com/sesac/developer_study_platform/Users.kt
  app/src/main/res/drawable/btn_join_study.xml
  app/src/main/res/drawable/btn_study_list.xml
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_arrow_next.xml
  app/src/main/res/drawable/ic_calendar_fill.xml
  app/src/main/res/drawable/ic_human.xml
  app/src/main/res/drawable/selector_join_study.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_join_study_list.xml
  app/src/main/res/layout/item_study_list.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: feat, design

#37 채팅 화면 레이아웃 구현
  app/src/main/res/drawable/bg_message_input.xml
  app/src/main/res/drawable/bg_message_receiver.xml
  app/src/main/res/drawable/bg_message_sender.xml
  app/src/main/res/drawable/bg_send_message.xml
  app/src/main/res/drawable/ic_arrow_upward.xml
  app/src/main/res/drawable/ic_crown.xml
  app/src/main/res/drawable/ic_plus_message.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/layout/item_message_receiver.xml
  app/src/main/res/layout/item_message_sender.xml
  app/src/main/res/menu/menu_toolbar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: design

#39 스터디 만들기 화면 파이어베이스에 값 저장
  app/build.gradle.kts
  app/src/main/java/com/sesac/developer_study_platform/data/Study.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/studyform/StudyFormFragment.kt
Labels: feat

#41 채팅방 목록 화면 구현
  app/src/main/java/com/sesac/developer_study_platform/data/UserChatRoom.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/ChatRoomClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/category/CategoryAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/category/CategoryFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/chatroom/ChatRoomAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/chatroom/ChatRoomFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/StudyAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/login/LoginFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/main/MainActivity.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/studyform/DayTimeAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/studyform/StudyFormFragment.kt
  app/src/main/res/drawable/bg_unread_count.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/item_chat_room.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
Labels: feat, design

#47 북마크 화면 및 기능 구현
  app/build.gradle.kts
  app/src/main/java/com/sesac/developer_study_platform/StudyApplication.kt
  app/src/main/java/com/sesac/developer_study_platform/data/Study.kt
  app/src/main/java/com/sesac/developer_study_platform/data/local/AppDatabase.kt
  app/src/main/java/com/sesac/developer_study_platform/data/local/BookmarkDao.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/BookmarkClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/bookmark/BookmarkAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/bookmark/BookmarkFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/DetailFragment.kt
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/drawable/ic_heart_fill.xml
  app/src/main/res/drawable/selector_heart.xml
  app/src/main/res/layout/fragment_bookmark.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: feat, design

#48 프로필 화면 구현
  app/src/main/java/com/sesac/developer_study_platform/data/Repository.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/GithubService.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/DetailFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/main/MainActivity.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/ProfileFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/RepositoryAdapter.kt
  app/src/main/res/drawable/ic_divider.xml
  app/src/main/res/drawable/ic_export.xml
  app/src/main/res/drawable/ic_fork.xml
  app/src/main/res/drawable/ic_issue.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_repository.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feat, design

#49 다이얼로그 구현
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/DetailFragment.kt
  app/src/main/res/drawable/bg_dialog.xml
  app/src/main/res/drawable/bg_dialog_no.xml
  app/src/main/res/drawable/bg_dialog_yes.xml
  app/src/main/res/layout/dialog_exit.xml
  app/src/main/res/layout/dialog_export.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/dialog_warning.xml
  app/src/main/res/values/strings.xml
Labels: feat, design

#50 홈화면 참여 스터디 목록 null 처리
  app/src/main/java/com/sesac/developer_study_platform/ui/SpaceItemDecoration.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: fix

#58 각 화면 코드 개선
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/assets/github-language-colors.json
  app/src/main/java/com/sesac/developer_study_platform/Day.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyApplication.kt
  app/src/main/java/com/sesac/developer_study_platform/data/Repository.kt
  app/src/main/java/com/sesac/developer_study_platform/data/Study.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/local/AppDatabase.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/local/BookmarkDao.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/GithubService.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/BookmarkClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/ChatRoomClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/DayTimeClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/SearchClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/StudyClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/UserStudyClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/bookmark/BookmarkAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/bookmark/BookmarkFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/category/CategoryAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/category/CategoryFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/chatroom/ChatRoomAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/chatroom/ChatRoomFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/common/GridSpaceItemDecoration.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/common/SpaceItemDecoration.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/common/StudyAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/common/StudyClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/DetailFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/login/LoginFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/main/MainActivity.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mystudy/MyStudyAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mystudy/MyStudyFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/ProfileFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/RepositoryAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/search/SearchFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/searchcategory/SearchCategoryFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/searchresult/SearchAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/searchresult/SearchResultFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/studyform/CustomTextWatcher.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/studyform/DayTimeAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/studyform/DayTimeClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/studyform/StudyFormFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/util/DateFormats.kt
  app/src/main/java/com/sesac/developer_study_platform/util/Extensions.kt
  app/src/main/java/com/sesac/developer_study_platform/util/StringExtensions.kt
  app/src/main/java/com/sesac/developer_study_platform/util/StudyExtensions.kt
  app/src/main/java/com/sesac/developer_study_platform/util/ViewExtensions.kt
  app/src/main/res/layout/fragment_bookmark.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_study.xml
  app/src/main/res/layout/fragment_study_form.xml
  app/src/main/res/layout/item_repository.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: fix, refactor

#57 마이페이지 레이아웃
  app/build.gradle.kts
  app/src/main/java/com/sesac/developer_study_platform/ui/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  gradle.properties
  settings.gradle.kts
Labels: design

#61 스터디 상세 화면 아키텍처 패턴 적용
  app/build.gradle.kts
  app/src/main/java/com/sesac/developer_study_platform/Event.kt
  app/src/main/java/com/sesac/developer_study_platform/StudyApplication.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/local/BookmarkRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/BindingAdapters.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/DetailFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/DetailViewModel.kt
  app/src/main/res/layout/fragment_detail.xml
Labels: refactor

#67 홈 화면 아키텍처 패턴 적용
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/BindingAdapters.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
Labels: refactor

#64 나의 스터디 목록 화면 아키텍처 패턴 적용
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/BindingAdapters.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/common/StudyAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/DetailViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mystudy/MyStudyFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mystudy/MyStudyViewModel.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/item_study.xml
Labels: refactor
