Repository android-team-02/developer-study-platform, pull requests merged in 2024-02, with the labels that each got.

#68 마이페이지 기능 구현(달력 커스텀, 내 정보)
  app/src/main/java/com/sesac/developer_study_platform/ui/mypage/DotSpanDecorator.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mypage/TodayDecorator.kt
  app/src/main/java/com/sesac/developer_study_platform/util/StringExtensions.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat

#56 채팅 기능 구현(이미지, 시스템 메시지)
  app/src/main/java/com/sesac/developer_study_platform/data/Message.kt
  app/src/main/java/com/sesac/developer_study_platform/data/Study.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/ImageAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MessageAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MessageFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/ViewHolder.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/ViewType.kt
  app/src/main/java/com/sesac/developer_study_platform/util/StringExtensions.kt
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/layout/item_image.xml
  app/src/main/res/layout/item_image_receiver.xml
  app/src/main/res/layout/item_image_sender.xml
  app/src/main/res/menu/menu_toolbar.xml
  app/src/main/res/values/strings.xml
Labels: feat, design

#72 검색, 검색 결과 목록 화면 아키텍처 패턴 적용
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/search/SearchFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/search/SearchViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/searchresult/SearchAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/searchresult/SearchResultFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/searchresult/SearchResultViewModel.kt
  app/src/main/res/layout/item_search.xml
Labels: refactor

#79 마이페이지 아키텍처 패턴 적용
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/BindingAdapters.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mypage/DotSpanDecorator.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mystudy/MyStudyViewModel.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: refactor

#80 채팅방 목록 화면 아키텍처 패턴 적용
  app/src/main/java/com/sesac/developer_study_platform/data/ChatRoom.kt
  app/src/main/java/com/sesac/developer_study_platform/data/UserChatRoom.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/BindingAdapters.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/chatroom/ChatRoomAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/chatroom/ChatRoomFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/chatroom/ChatRoomViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/util/StringExtensions.kt
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/item_chat_room.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feat, refactor, design

#84 채팅메뉴 레이아웃
  app/src/main/res/drawable/ic_exit.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/layout/item_chat_menu.xml
  app/src/main/res/values/strings.xml
Labels: design

#92 채팅메뉴 기능구현
  app/src/main/java/com/sesac/developer_study_platform/data/User.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MenuAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MessageFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/StudyMemberClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/ProfileFragment.kt
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat

#81 로그인 화면 아키텍처 패턴 적용
  app/build.gradle.kts
  app/src/main/java/com/sesac/developer_study_platform/StudyApplication.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/local/UserPreferencesRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/GithubRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/GithubService.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/login/LoginFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/login/LoginViewModel.kt
Labels: refactor

#85 프로필 화면 아키텍처 패턴 적용
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/GithubRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/BindingAdapters.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/DetailFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MessageFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/ProfileFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/RepositoryAdapter.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_repository.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat, refactor

#93 채팅 화면 아키텍처 패턴 적용
  app/src/main/java/com/sesac/developer_study_platform/data/Message.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/BindingAdapters.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/main/MainActivity.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/ImageAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MessageFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MessageViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/ViewHolder.kt
  app/src/main/res/layout/item_image.xml
  app/src/main/res/layout/item_image_receiver.xml
  app/src/main/res/layout/item_image_sender.xml
  app/src/main/res/layout/item_message_receiver.xml
  app/src/main/res/layout/item_message_sender.xml
Labels: feat, refactor

#102 채팅 화면 날짜와 스터디 멤버 시스템 메시지 분리
  app/src/main/java/com/sesac/developer_study_platform/ui/BindingAdapters.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MessageFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/util/StringExtensions.kt
  app/src/main/res/layout/item_image_receiver.xml
  app/src/main/res/layout/item_image_sender.xml
  app/src/main/res/layout/item_message_receiver.xml
  app/src/main/res/layout/item_message_sender.xml
Labels: fix

#104 로그아웃 다이얼로그 구현
  app/src/main/java/com/sesac/developer_study_platform/data/source/local/UserPreferencesRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/login/LoginViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mypage/LogoutDialogFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mypage/LogoutDialogViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mypage/MyPageFragment.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: feat

#106 스터디 만들기 클릭 시 채팅방으로 이동
  app/src/main/java/com/sesac/developer_study_platform/data/ChatRoom.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/chatroom/ChatRoomAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/studyform/StudyFormFragment.kt
  app/src/main/res/layout/item_chat_room.xml
Labels: fix, feat

#109 나의 스터디 목록 화면 Room 캐싱 적용
  app/src/main/java/com/sesac/developer_study_platform/ui/mystudy/MyStudyFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mystudy/MyStudyViewModel.kt
Labels: feat

#108 각 화면에서 채팅방으로 이동
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/DetailFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/DetailViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mystudy/MyStudyFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mystudy/MyStudyViewModel.kt
Labels: feat

#100 홈화면 Room 캐싱 적용
  app/src/main/java/com/sesac/developer_study_platform/StudyApplication.kt
  app/src/main/java/com/sesac/developer_study_platform/data/Converters.kt
  app/src/main/java/com/sesac/developer_study_platform/data/Study.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/local/AppDatabase.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/local/MyStudyDao.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/local/MyStudyRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mypage/MyPageViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mystudy/MyStudyFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mystudy/MyStudyViewModel.kt
  app/src/main/res/layout/item_study.xml
Labels: feat

#96 프로필 레포지토리 목록 웹뷰 구현
  app/src/main/java/com/sesac/developer_study_platform/data/Repository.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/main/MainActivity.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/ProfileFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/ProfileViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/RepositoryAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/RepositoryClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/WebViewFragment.kt
  app/src/main/res/layout/fragment_webview.xml
  app/src/main/res/layout/item_repository.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat

#110 스터디 참여 다이얼로그 피드백 반영
  app/src/main/java/com/sesac/developer_study_platform/data/Study.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/DetailFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/DetailViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/JoinStudyDialogFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/JoinStudyDialogViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/main/MainActivity.kt
  app/src/main/res/navigation/nav_graph.xml
Labels: feat

#112 채팅 관련 오류
  app/src/main/java/com/sesac/developer_study_platform/data/Message.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/BindingAdapters.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MessageFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MessageViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/util/DateFormats.kt
  app/src/main/java/com/sesac/developer_study_platform/util/LongExtensions.kt
  app/src/main/java/com/sesac/developer_study_platform/util/StringExtensions.kt
  app/src/main/res/layout/item_image_receiver.xml
  app/src/main/res/layout/item_image_sender.xml
  app/src/main/res/layout/item_message_receiver.xml
  app/src/main/res/layout/item_message_sender.xml
Labels: fix

#116 자동 스크롤 오류 해결
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MessageFragment.kt
Labels: fix

#118 홈화면 및 상세화면
  app/src/main/java/com/sesac/developer_study_platform/ui/BindingAdapters.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/DetailViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeFragment.kt
Labels: fix

#120 오프라인 상태일 때 문구 표시
  app/src/main/java/com/sesac/developer_study_platform/ui/bookmark/BookmarkFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/chatroom/ChatRoomFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/detail/DetailFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MessageFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/mystudy/MyStudyFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/ProfileFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/search/SearchFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/searchcategory/SearchCategoryFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/searchresult/SearchResultFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/studyform/StudyFormFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/util/NetworkUtil.kt
  app/src/main/res/layout/fragment_bookmark.xml
  app/src/main/res/layout/fragment_chat_room.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_my_study.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_category.xml
  app/src/main/res/layout/fragment_search_result.xml
  app/src/main/res/layout/fragment_study_form.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feat, design

#124 채팅목록 최신순으로 정렬
  app/src/main/java/com/sesac/developer_study_platform/ui/chatroom/ChatRoomViewModel.kt
Labels: fix

#125 그리드 레이아웃 아이템 간격 오류 수정
  app/src/main/java/com/sesac/developer_study_platform/ui/common/GridSpaceItemDecoration.kt
Labels: fix

#128 채팅방 내보내기 다이얼로그 구현
  app/src/main/java/com/sesac/developer_study_platform/data/User.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/remote/StudyService.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/main/MainActivity.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MenuAdapter.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MessageFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/StudyMemberClickListener.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/BanDialogFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/BanDialogViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/ProfileFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/profile/ProfileViewModel.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat

#127 채팅방 나가기 다이얼로그 구현
  app/src/main/java/com/sesac/developer_study_platform/ui/main/MainActivity.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/ExitDialogFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/ExitDialogViewModel.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MessageFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/message/MessageViewModel.kt
  app/src/main/res/layout/dialog_exit.xml
  app/src/main/res/layout/fragment_message.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feat

#130 홈 화면 룸을 이용한 캐싱 구현
  app/src/main/java/com/sesac/developer_study_platform/data/source/local/MyStudyDao.kt
  app/src/main/java/com/sesac/developer_study_platform/data/source/local/MyStudyRepository.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeFragment.kt
  app/src/main/java/com/sesac/developer_study_platform/ui/home/HomeViewModel.kt
Labels: feat
